// ==============================================================================
// <auto-generated>
//     THIS CODE WAS AUTOMATICALLY GENERATED BY SAWC LOCALIZATION PIPELINE.
//     CHANGES TO THIS FILE WILL BE LOST IF THE CODE IS REGENERATED.
// </auto-generated>
// ==============================================================================
using System;
using UnityEngine;

namespace SAWC.Editor.Localization
{
    [CreateAssetMenu(fileName = "NewLanguage", menuName = "SAWC/Editor/Language Asset")]
    public class LanguageAsset : ScriptableObject
    {
        public string LanguageName = "English";

        public TranslationEntry Configuration;
        public TranslationEntry Crouch;
        public TranslationEntry CrouchSettingsCanCrouch;
        public TranslationEntry CrouchSettingsCanJumpWhileCrouching;
        public TranslationEntry CrouchSettingsCrouchHeight;
        public TranslationEntry CrouchSettingsCrouchSpeed;
        public TranslationEntry CrouchSettingsEnvironmentMask;
        public TranslationEntry CrouchSettingsStandingHeight;
        public TranslationEntry DashboardAssignConfig;
        public TranslationEntry DashboardCharacterSettingsLabel;
        public TranslationEntry DashboardErrorNoSettingsField;
        public TranslationEntry DashboardValidationCrouchHeight;
        public TranslationEntry DashboardValidationCrouchSpeed;
        public TranslationEntry DashboardValidationGravity;
        public TranslationEntry DashboardValidationSprint;
        public TranslationEntry Editor_ActiveLangLabel;
        public TranslationEntry Editor_DocButton;
        public TranslationEntry Editor_DocMessage;
        public TranslationEntry Editor_Hello;
        public TranslationEntry Editor_InstalledPacksLabel;
        public TranslationEntry Jump;
        public TranslationEntry JumpSettingsAirControlMultiplier;
        public TranslationEntry JumpSettingsCanJump;
        public TranslationEntry JumpSettingsCeilingBounceVelocity;
        public TranslationEntry JumpSettingsCoyoteTime;
        public TranslationEntry JumpSettingsEnableAutoJump;
        public TranslationEntry JumpSettingsJumpBufferTime;
        public TranslationEntry JumpSettingsJumpCooldownDuration;
        public TranslationEntry JumpSettingsJumpForce;
        public TranslationEntry Movement;
        public TranslationEntry MovementSettingsAccelerationCurve;
        public TranslationEntry MovementSettingsAllowedSprintDirections;
        public TranslationEntry MovementSettingsBaseAcceleration;
        public TranslationEntry MovementSettingsBaseDeceleration;
        public TranslationEntry MovementSettingsCanMove;
        public TranslationEntry MovementSettingsCanSprint;
        public TranslationEntry MovementSettingsDecelerationCurve;
        public TranslationEntry MovementSettingsMinMoveThreshold;
        public TranslationEntry MovementSettingsMoveSpeed;
        public TranslationEntry MovementSettingsSprintSpeed;
        public TranslationEntry MovementSettingsUseInertia;
        public TranslationEntry Physics;
        public TranslationEntry PhysicsSettingsFallMultiplier;
        public TranslationEntry PhysicsSettingsGravity;
        public TranslationEntry PhysicsSettingsGroundedGravity;
        public TranslationEntry PhysicsSettingsTerminalVelocity;
        public TranslationEntry PhysicsSettingsUseGravity;
        public TranslationEntry Rotation;
        public TranslationEntry RotationSettingsMovementRotationSmoothTime;
        public TranslationEntry RotationSettingsRotateWithMovement;
        public TranslationEntry RotationSettingsStrafeRotationSmoothTime;
        public TranslationEntry Thresholds;
        public TranslationEntry ThresholdSettingsAirStateDebounceTime;
        public TranslationEntry ThresholdSettingsFallVelocityThreshold;
        public TranslationEntry ThresholdSettingsIdleTransitionMultiplier;
        public TranslationEntry ThresholdSettingsInputThreshold;
        public TranslationEntry ThresholdSettingsSprintDirectionThreshold;
        public TranslationEntry ThresholdSettingsVelocityThreshold;
        public TranslationEntry ThresholdSettingsVerticalVelocityThreshold;


        private void OnValidate()
        {
            SAWC.Editor.Localization.SAWCLoc.System.NotifyLanguageChanged();
        }
    }
}
