using SAWC.Localization;
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using UnityEditor;
using UnityEngine;

namespace SAWC.Editor.Localization
{
    public static class LanguageAssetGenerator
    {
        public static void RegenerateFields()
        {
            SortedSet<string> keys = new();

            string[] configGuids = AssetDatabase.FindAssets($"t:{nameof(SAWCEditorKeys)}");
            if (configGuids.Length > 0)
            {
                string configPath = AssetDatabase.GUIDToAssetPath(configGuids[0]);
                var config = AssetDatabase.LoadAssetAtPath<SAWCEditorKeys>(configPath);
                if (config != null && config.Keys != null)
                {
                    foreach (var k in config.Keys)
                    {
                        if (!string.IsNullOrEmpty(k))
                        {
                            keys.Add(k);
                        }
                    }
                }
            }
            else
            {
                Debug.LogWarning($"{nameof(SAWCEditorKeys)} asset not found.");
            }

            HashSet<Type> processedTypes = new();
            var fieldsWithAttribute = TypeCache.GetFieldsWithAttribute<LocAttribute>();

            foreach (var field in fieldsWithAttribute)
            {
                var fieldType = field.FieldType;
                var asmName = fieldType.Assembly.GetName().Name ?? string.Empty;

                if (!asmName.StartsWith("Unity", StringComparison.OrdinalIgnoreCase) &&
                    !asmName.StartsWith("System", StringComparison.OrdinalIgnoreCase) &&
                    !asmName.StartsWith("mscorlib", StringComparison.OrdinalIgnoreCase))
                {
                    if (!processedTypes.Add(fieldType))
                        continue;

                    var subFields = fieldType.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
                    foreach (var subField in subFields)
                    {
                        string fieldName = subField.Name;
                        if (fieldName.Length > 0 && char.IsLower(fieldName[0]))
                            fieldName = char.ToUpper(fieldName[0]) + fieldName.Substring(1);

                        keys.Add($"{fieldType.Name}{fieldName}");
                    }
                }
                else
                {
                    string fieldName = field.Name;
                    if (fieldName.Length > 0 && char.IsLower(fieldName[0]))
                        fieldName = char.ToUpper(fieldName[0]) + fieldName.Substring(1);

                    keys.Add($"{field.DeclaringType.Name}{fieldName}");
                }
            }

            string[] scriptGuids = AssetDatabase.FindAssets($"{nameof(LanguageAsset)} t:MonoScript");
            if (scriptGuids.Length == 0)
            {
                Debug.LogError($"{nameof(LanguageAsset)}.cs file not found в проекте.");
                return;
            }
            string filePath = AssetDatabase.GUIDToAssetPath(scriptGuids[0]);

            if (string.IsNullOrEmpty(filePath))
            {
                Debug.LogError($"{nameof(LanguageAsset)}.cs file not found.");
                return;
            }

            System.Text.StringBuilder sb = new();
            sb.AppendLine("// ==============================================================================");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     THIS CODE WAS AUTOMATICALLY GENERATED BY SAWC LOCALIZATION PIPELINE.");
            sb.AppendLine("//     CHANGES TO THIS FILE WILL BE LOST IF THE CODE IS REGENERATED.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("// ==============================================================================");
            sb.AppendLine("using System;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace SAWC.Editor.Localization");
            sb.AppendLine("{");
            sb.AppendLine("    [CreateAssetMenu(fileName = \"NewLanguage\", menuName = \"SAWC/Editor/Language Asset\")]");
            sb.AppendLine("    public class LanguageAsset : ScriptableObject");
            sb.AppendLine("    {");
            sb.AppendLine("        public string LanguageName = \"English\";");
            sb.AppendLine();

            foreach (var key in keys)
            {
                sb.AppendLine($"        public TranslationEntry {key};");
            }

            sb.AppendLine();
            sb.AppendLine();
            sb.AppendLine("        private void OnValidate()");
            sb.AppendLine("        {");
            sb.AppendLine("            SAWC.Editor.Localization.SAWCLoc.System.NotifyLanguageChanged();");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(filePath, sb.ToString());
            AssetDatabase.Refresh();
            Debug.Log($"{nameof(LanguageAsset)} fields synchronized. Total keys: {keys.Count}");
        }
    }
}