using SAWC.Localization;
using SAWC.Core.Data;
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using UnityEditor;

namespace SAWC.Editor.Localization
{
    public static class LanguageAssetGenerator
    {
        private static readonly HashSet<Type> ValidStructures = new()
        {
            typeof(CharacterSettingsData),
            typeof(MovementSettings),
            typeof(JumpSettings),
            typeof(CrouchSettings),
            typeof(PhysicsSettings),
            typeof(RotationSettings),
            typeof(ThresholdSettings)
        };

        public static void RegenerateFields()
        {
            SortedSet<string> keys = new();

            string[] configGuids = AssetDatabase.FindAssets($"t:{nameof(SAWCEditorKeys)}");
            if (configGuids.Length > 0)
            {
                string configPath = AssetDatabase.GUIDToAssetPath(configGuids[0]);
                var config = AssetDatabase.LoadAssetAtPath<SAWCEditorKeys>(configPath);
                if (config != null && config.Keys != null)
                {
                    foreach (var k in config.Keys)
                    {
                        if (!string.IsNullOrEmpty(k)) keys.Add(k);
                    }
                }
            }

            var fieldsWithAttribute = TypeCache.GetFieldsWithAttribute<LocAttribute>();

            foreach (var field in fieldsWithAttribute)
            {
                var fieldType = field.FieldType;

                if (ValidStructures.Contains(fieldType))
                {
                    var subFields = fieldType.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
                    foreach (var subField in subFields)
                    {
                        keys.Add($"{fieldType.Name}{subField.Name}");
                    }
                }
                else
                {
                    keys.Add($"{field.DeclaringType.Name}{field.Name}");
                }
            }

            string[] scriptGuids = AssetDatabase.FindAssets($"{nameof(LanguageAsset)} t:MonoScript");
            if (scriptGuids.Length == 0) return;

            string filePath = AssetDatabase.GUIDToAssetPath(scriptGuids[0]);
            if (string.IsNullOrEmpty(filePath)) return;

            System.Text.StringBuilder sb = new();
            sb.AppendLine("// ==============================================================================");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     THIS CODE WAS AUTOMATICALLY GENERATED BY SAWC LOCALIZATION PIPELINE.");
            sb.AppendLine("//     CHANGES TO THIS FILE WILL BE LOST IF THE CODE IS REGENERATED.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("// ==============================================================================");
            sb.AppendLine("using System;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace SAWC.Editor.Localization");
            sb.AppendLine("{");
            sb.AppendLine("    public class LanguageAsset : ScriptableObject");
            sb.AppendLine("    {");
            sb.AppendLine("        public string LanguageName = \"English\";");
            sb.AppendLine();

            foreach (var key in keys)
            {
                sb.AppendLine($"        public TranslationEntry {key};");
            }

            sb.AppendLine();
            sb.AppendLine("        private void OnValidate()");
            sb.AppendLine("        {");
            sb.AppendLine("            SAWC.Editor.Localization.SAWCLoc.System.NotifyLanguageChanged();");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(filePath, sb.ToString());
            AssetDatabase.Refresh();
        }
    }
}